FROM mcr.microsoft.com/devcontainers/base:ubuntu

WORKDIR /workspace

RUN apt update && apt install -y \
  cmake \ 
  g++ \ 
  wget \ 
  unzip \ 
  libwebkit2gtk-4.1-dev \ 
  build-essential \ 
  curl \ 
  wget \ 
  file \ 
  libxdo-dev \ 
  libssl-dev \ 
  libayatana-appindicator3-dev \ 
  librsvg2-dev \ 
  gh 
